<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutputPath>bin\</OutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.8.0" />
    <PackageReference Include="Blackbaud.Blob.Storage" Version="8.2025.409.3" />
    <PackageReference Include="Blackbaud.Core.App" Version="8.*" />
    <PackageReference Include="Blackbaud.Cosmos" Version="10.2025.1217.1" />
    <PackageReference Include="Blackbaud.Gbs.Core" Version="0.2025.1215.1" />
    <PackageReference Include="Blackbaud.Permissions.Resolver" Version="8.*" />
  </ItemGroup>

  <Target Name="CopySkyConfig" AfterTargets="Compile">
    <Copy SourceFiles="$(ProjectDir)..\..\skyconfig.json" DestinationFolder="$(OutDir)" />
  </Target>

  <Target Name="PublishSkyConfig" AfterTargets="Publish">
    <Copy SourceFiles="$(ProjectDir)..\..\skyconfig.json" DestinationFolder="$(PublishDir)" />
  </Target>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>$(AssemblyName).UnitTests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
